name: Test

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installing packages
        run: npm ci

      - name: Prepare
        run: npm run prepare

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
